version: '3.1' 
services:
  centos-docker:
    image: openkbs/centos-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centos-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    #env_file:
    #  - .env
    volumes:
      - ./workspace:/home/developer/workspace


